### ISSUE TITLE
dmhy ls doesn't show latest

### ISSUE THREAD

**Issue by maple3142** [FlandreDaisuki/dmhy-subscribe#2]
When I use `dmhy ls`, it shows:
```
vid | latest | name

FEY |   --   | 搖曳露營
```

version:
```
$ node -v
v9.2.1
$ dmhy -V
0.3.10
```

**Comment by FlandreDaisuki** [comment]
You just add '搖曳露營' into your subscribe list. The only action you should do is call `dmhy`. This make check those non-downloaded magnets to download.

The result of '搖曳露營' has messy threads, the keyword should be more specific. See following examples:

The keyword `搖曳露營` is bad：
![_002](https://user-images.githubusercontent.com/5981459/36632038-da6c56a8-19bb-11e8-82f8-feb1e9f1875b.png)

The keyword `搖曳露營,喵萌奶茶屋` is bad either：
![_003](https://user-images.githubusercontent.com/5981459/36632055-19cd89c0-19bc-11e8-89d2-64f2657c8a74.png)

The keyword `搖曳露營,喵萌奶茶屋,繁體` is very good：
![_004](https://user-images.githubusercontent.com/5981459/36632065-60b09800-19bc-11e8-9b81-1160c25255e6.png)

The keyword `搖曳露營△,DHR,繁體,720P` is very good too：
![_005](https://user-images.githubusercontent.com/5981459/36632103-0158d88a-19bd-11e8-9e75-94461c1f8d02.png)

**Comment by FlandreDaisuki** [comment]
Update readme to v0.4.0 and `dmhy -h`. There are simple examples.
If you have other questions, feel free to open issue or comment below.
