### ISSUE TITLE
下載器啟動失敗卻顯示下載成功

### ISSUE THREAD

**Issue by FlandreDaisuki** [FlandreDaisuki/dmhy-subscribe#21]
- OS: 大概是 Linux
- NodeJS: ?
- CLI version: 0.6.4
- Error message 錯誤訊息:
![photo_2018-04-10_12-47-12](https://user-images.githubusercontent.com/5981459/38536757-6cb89188-3cbd-11e8-8917-7a8e49d7cc4d.jpg)
當 downloader 為 system 且系統找不到 magnet 的關聯程式時會出現此錯誤

**Comment by FlandreDaisuki** [comment]
https://github.com/FlandreDaisuki/dmhy-subscribe/blob/master/src/downloaders/system.js#L12
感覺無解... 被 exit(4) 之後，Promise 好像也是走 resolve

**Comment by maple3142** [comment]
把 `catch` 拿掉，或是在 `catch` 裡面再 throw 一次
其他的下載器也應該這樣做才對，之前沒注意到= =

**Comment by Inndy** [comment]
@FlandreDaisuki process 跑不起來才是 error，process 跑起來了，檢查 exit code 非 0 吧

**Comment by FlandreDaisuki** [comment]
@maple3142 
是因為我們之前用 `spawn` 現在用 `require` 的關係嘛？

https://github.com/FlandreDaisuki/dmhy-subscribe/blob/4e859667b4ba456feaf052bb3f32908b08162ef2/src/utils.js#L263-L266

但這樣可能就變成四個 downloader 都用檢查 exit 的值來判斷成功失敗？
