### ISSUE TITLE
關於 yargs 的說明

### ISSUE THREAD

**Issue by maple3142** [FlandreDaisuki/dmhy-subscribe#22]
- OS: win10 x64
- NodeJS: 9.2.1
- CLI version: 0.6.6

在 Windows 下輸入 `dmhy -h` 會出現這些東西，指令的名稱都會變成 `cli.js`
![image](https://user-images.githubusercontent.com/9370547/38561474-bceb8bf4-3d0a-11e8-9f1b-eb9b27f506e8.png)

根據 https://github.com/yargs/yargs/issues/538 應該可以透過
```javascript
yargs.usage('dmhy [command] [options]') //用 dmhy 取代 $0
```
來改，不過這只能改到使用方法部分的名稱，其他東西還沒在 yargs 那邊找到資訊
![image](https://user-images.githubusercontent.com/9370547/38561606-04adde6a-3d0b-11e8-8710-aaa57e8d178c.png)

**Comment by FlandreDaisuki** [comment]
對吼 windows 的 npm bin 是用 dmhy.cmd 來執行 `node cli.js`
這樣 `yargs` 拿到的前兩個 argv 就會是 node 路徑跟 cli.js 路徑

Linux 的 npm bin 是用 symbolic link 的方式，所以沒問題...

原本想說 Linux 有人用 `ln -s` 也會顯示正確的名稱，
看來還是寫死好了 Orz

**Comment by FlandreDaisuki** [comment]
Fixed from `v0.6.7`
