### ISSUE TITLE
[建議] 考慮改用 rss 來抓取?

### ISSUE THREAD

**Issue by maple3142** [FlandreDaisuki/dmhy-subscribe#36]
如題，目前是直接抓取網頁來搜尋和取得連接的，不過後來發現它們其實有給 rss 的連結:
`http://share.dmhy.org/topics/rss/rss.xml?keyword=哥布林殺手&sort_id=2`
裡面都是 XML，也不太需要擔心哪天網站改了會壞掉的問題

**Comment by FlandreDaisuki** [comment]
感覺是可以啦.. 只是最近追的番沒有當初多就有點不想動www

感覺是把 crawler.js 改成 HTMLCrawler 
上面加一層 Crawler interface 底下加上 atomCrawler 就好了

~~太久沒動這份 code 了 有點怕~~
